# fly.toml app configuration file generated for random-poem on 2025-07-31T19:04:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'random-poem'
primary_region = 'iad'

[build]

[deploy]
  strategy = 'canary'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '1m0s'
    timeout = '1s'
    grace_period = '5s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
